added route to update skill test question
OpenSouceCode/Backend pull request #103
Opened 2020-09-19 18:06 UTC by Dishebh

Fixes #90

2020-09-20 06:01 UTC, irshadjsr21 requested changes
Check if correctIndex is valid here also.

2020-09-20 09:15 UTC, Dishebh commented
@irshadjsr21 ready for review

2020-09-20 10:17 UTC, irshadjsr21 requested changes

2020-09-20 10:17 UTC, irshadjsr21 commented on src/validators/skillTest.js
> +          correctIndex >= 0 && correctIndex < req.body.options.length,
Since the `options` array is optional, it might not be available in the req.body. So you need to check it from the stored `options`.

2020-09-21 05:29 UTC, irshadjsr21 approved these changes

2020-09-21 05:29 UTC, irshadjsr21 commented on src/controllers/v1/skillTest.js
> +      const skillTestQuestion = await SkillTestQuestion.findById(questionId);
Why are we getting the skill test question 2 times?

2020-09-21 06:52 UTC, Dishebh commented on src/controllers/v1/skillTest.js
> +      const skillTestQuestion = await SkillTestQuestion.findById(questionId);
updated the controller :+1:

2020-09-21 06:52 UTC, merged