added route to display all skill tests
OpenSouceCode/Backend pull request #108
Opened 2020-09-21 12:37 UTC by Dishebh

Fixes #95

2020-09-21 13:24 UTC, irshadjsr21 requested changes

2020-09-21 13:24 UTC, irshadjsr21 commented on src/controllers/v1/skillTest.js
> +    }
Instead of having if conditions here, create a `filterObj` variable which will be used as `SkillTest.find(filterObj)`

2020-09-21 13:24 UTC, irshadjsr21 commented on src/controllers/v1/skillTest.js
> +    const { page = 1, per_page = 10, isPublished = false } = req.query;
`isPublished` will be a `string` so you need to check it's value in the if conditions.

2020-09-23 07:48 UTC, irshadjsr21 requested changes

2020-09-23 07:48 UTC, irshadjsr21 commented on src/controllers/v1/skillTest.js
> +        ? {}
Set `isPublished` to `true` here.

2020-09-23 08:21 UTC, Dishebh commented on src/controllers/v1/skillTest.js
> +        ? {}
Made changes :+1: , this should solve the duplicate key error as well

2020-09-23 14:52 UTC, irshadjsr21 approved these changes

2020-09-23 14:52 UTC, merged