added poolSize config to mongoose connection and added trim flag on n…
OpenSouceCode/Backend pull request #38
Opened 2020-08-26 11:16 UTC by sahiljamwal

…ame field in userSchema

As mentioned in the issue kindly review the Changes.

2020-08-26 19:52 UTC, irshadjsr21 requested changes

2020-08-26 19:52 UTC, irshadjsr21 commented on .env.example
> +MONGO_POOLSIZE=10
Please rename the `env` variable from `MONGO_POOLSIZE` to `DB_POOLSIZE` to be consistent of the naming.

2020-08-26 20:08 UTC, sahiljamwal commented
Please review now  completed the necessary changes

2020-08-27 07:38 UTC, irshadjsr21 approved these changes

2020-08-27 07:38 UTC, merged