added GET route to get discussion by id
OpenSouceCode/Backend pull request #78
Opened 2020-09-13 15:35 UTC by Dishebh

Fixes #68

2020-09-13 15:36 UTC, irshadjsr21 requested changes
Use `populate` to populate the `userId` field with user data.

2020-09-13 15:49 UTC, Dishebh commented
@irshadjsr21 added populate

2020-09-14 09:42 UTC, irshadjsr21 requested changes

2020-09-14 09:42 UTC, irshadjsr21 commented on src/controllers/v1/discussion.js
> +      .populate('userId', 'name profileImage title role')
In User model, create a function, getDiscussionFields which will return an array containing `_id`, `name` & `profileImage`. And use that here.

2020-09-16 05:24 UTC, irshadjsr21 approved these changes

2020-09-16 05:24 UTC, merged