added route to get all discussions
OpenSouceCode/Backend pull request #83
Opened 2020-09-16 06:17 UTC by Dishebh

Fixes #72

2020-09-16 12:05 UTC, irshadjsr21 requested changes
Add pagination here.

2020-09-16 13:16 UTC, irshadjsr21 requested changes

2020-09-16 13:16 UTC, irshadjsr21 commented on src/controllers/v1/discussion.js
> +    const { page = 1, per_page = 10 } = req.query;
req.query returns a string, you need to convert it to a number before doing mathamatical operations.

2020-09-16 16:03 UTC, Dishebh commented on src/controllers/v1/discussion.js
> +    const { page = 1, per_page = 10 } = req.query;
Operations are taking place, maybe due to type conversion

2020-09-17 06:21 UTC, irshadjsr21 approved these changes

2020-09-17 06:21 UTC, merged